"""Generate explicit optimizer facade signatures for static analysis."""

from pathlib import Path

from heavyball import optim
from heavyball.optim import HeavyBallOptimizer, _facade_hyperparameters


def _render_init(hyperparameters: tuple[tuple[str, type, object], ...]) -> list[str]:
    lines = [
        "    def __init__(",
        "        self,",
        "        params: Iterable[Tensor],",
        "        *,",
    ]
    lines.extend(
        f"        {name}: {annotation if isinstance(annotation, str) else annotation.__name__} = ...,"
        for name, annotation, _ in hyperparameters
    )
    lines.append("    ) -> None: ...")
    return lines


def render() -> str:
    lines = [
        "# GENERATED by heavyball/_autocomplete_stub.py -- do not edit by hand.",
        "",
        "from typing import Iterable, Sequence",
        "",
        "import os",
        "import torch",
        "from torch import Tensor",
        "from torch.optim import Optimizer",
        "",
        "from .core import Recipe, Route",
        "",
        "class HeavyBallOptimizer(Optimizer):",
        "    def __init__(",
        "        self,",
        "        params: Iterable[Tensor],",
        "        recipe: Recipe | Route | None = ...,",
        "        **hyper,",
        "    ) -> None: ...",
        "    def dcp_save(self, checkpoint_dir: str | os.PathLike[str]) -> None: ...",
        "    def dcp_load(self, checkpoint_dir: str | os.PathLike[str]) -> None: ...",
    ]
    for name in optim.__all__:
        facade = getattr(optim, name)
        if not (isinstance(facade, type) and issubclass(facade, HeavyBallOptimizer) and facade is not HeavyBallOptimizer):
            continue
        lines.extend(("", "", f"class {name}(HeavyBallOptimizer):"))
        lines.extend(_render_init(_facade_hyperparameters(facade.recipe)))

    lines.extend(("", "", "__all__ = ["))
    lines.extend(f'    "{name}",' for name in optim.__all__)
    lines.extend(("]", ""))
    return "\n".join(lines)


if __name__ == "__main__":
    Path(__file__).with_name("optim.pyi").write_text(render(), encoding="utf-8")
