"""Generate explicit optimizer facade signatures for static analysis."""

from pathlib import Path

from heavyball import optim
from heavyball.optim import HeavyBallOptimizer, _facade_hyperparameters

_PARAMS_TYPE = "Iterable[Tensor] | Iterable[Mapping[str, object]]"


def render() -> str:
    lines = [
        "# GENERATED by heavyball/_autocomplete_stub.py -- do not edit by hand.",
        "",
        "from typing import Callable, Iterable, Mapping, Sequence",
        "",
        "import os",
        "import torch",
        "from torch import Tensor",
        "from torch.optim import Optimizer",
        "",
        "from .core import Recipe, Route",
        "",
        "class HeavyBallOptimizer(Optimizer):",
        "    def __init__(",
        "        self,",
        f"        params: {_PARAMS_TYPE},",
        "        recipe: Recipe | Route | None = ...,",
        "        **hyper,",
        "    ) -> None: ...",
        "    def step(",
        "        self,",
        "        closure: Callable[[], Tensor] | None = None,",
        "        observed: Sequence[bool] | Mapping[Tensor, bool] | None = None,",
        "    ) -> Tensor | None: ...",
        "    def zero_grad(self, set_to_none: bool = False) -> None: ...",
        "    def train(self, mode: bool = True) -> HeavyBallOptimizer: ...",
        "    def eval(self) -> HeavyBallOptimizer: ...",
        "    def produce(self, param: Tensor, name: str, value: Tensor) -> None: ...",
        "    @classmethod",
        "    def fsdp2(cls, model: object, **hyper) -> HeavyBallOptimizer: ...",
        "    def dcp_save(self, checkpoint_dir: str | os.PathLike[str]) -> None: ...",
        "    def dcp_load(self, checkpoint_dir: str | os.PathLike[str]) -> None: ...",
    ]
    for name in optim.__all__:
        facade = getattr(optim, name)
        if not (isinstance(facade, type) and issubclass(facade, HeavyBallOptimizer) and facade is not HeavyBallOptimizer):
            continue
        lines.extend(("", "", f"class {name}(HeavyBallOptimizer):"))
        lines.extend((
            "    def __init__(",
            "        self,",
            f"        params: {_PARAMS_TYPE},",
            "        *,",
        ))
        for hyper_name, annotation, default in _facade_hyperparameters(facade.recipe):
            if isinstance(annotation, str):
                rendered = annotation
            elif default is None:
                rendered = "float | None"
            else:
                rendered = annotation.__name__
            lines.append(f"        {hyper_name}: {rendered} = ...,")
        lines.append("    ) -> None: ...")

    if "SplitOpt" in optim.__all__:
        lines.extend((
            "",
            "",
            "class SplitOpt(Optimizer):",
            "    def __init__(self, specs: Sequence[dict[str, object]]) -> None: ...",
        ))

    lines.extend(("", "", "__all__ = ["))
    lines.extend(f'    "{name}",' for name in optim.__all__)
    lines.extend(("]", ""))
    return "\n".join(lines)


if __name__ == "__main__":
    Path(__file__).with_name("optim.pyi").write_text(render(), encoding="utf-8")
