# GENERATED by heavyball/_autocomplete_stub.py -- do not edit by hand.

from typing import Callable, Iterable, Mapping, Sequence

import os
import torch
from torch import Tensor
from torch.optim import Optimizer

from .core import Recipe, Route

class HeavyBallOptimizer(Optimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        recipe: Recipe | Route | None = ...,
        **hyper,
    ) -> None: ...
    def step(
        self,
        closure: Callable[[], Tensor] | None = None,
        observed: Sequence[bool] | Mapping[Tensor, bool] | None = None,
    ) -> Tensor | None: ...
    def zero_grad(self, set_to_none: bool = False) -> None: ...
    def train(self, mode: bool = True) -> HeavyBallOptimizer: ...
    def eval(self) -> HeavyBallOptimizer: ...
    def produce(self, param: Tensor, name: str, value: Tensor) -> None: ...
    @classmethod
    def fsdp2(cls, model: object, **hyper) -> HeavyBallOptimizer: ...
    def dcp_save(self, checkpoint_dir: str | os.PathLike[str]) -> None: ...
    def dcp_load(self, checkpoint_dir: str | os.PathLike[str]) -> None: ...


class ADOPT(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class AdEMAMix(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        beta3: float = ...,
        eps: float = ...,
        alpha: float = ...,
        beta3_warmup: float = ...,
        alpha_warmup: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class AdaMuon(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class AdamC(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        max_lr: float | None = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class AdamW(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class Aurora(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class CautiousAdamW(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class HeavyKLSOAP(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        shampoo_beta: float = ...,
        preconditioner_update_probability: float = ...,
        max_precond_dim: int = ...,
        init_factor: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class HeavyKLShampoo(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        preconditioner_update_probability: float = ...,
        max_precond_dim: int = ...,
        init_factor: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class HeavySOAP(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        shampoo_beta: float = ...,
        preconditioner_update_probability: float = ...,
        max_precond_dim: int = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class HeavySOAPAdEMAMix(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        shampoo_beta: float = ...,
        preconditioner_update_probability: float = ...,
        max_precond_dim: int = ...,
        beta3: float = ...,
        alpha: float = ...,
        beta3_warmup: float = ...,
        alpha_warmup: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class HeavySOAPNAdam(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        shampoo_beta: float = ...,
        preconditioner_update_probability: float = ...,
        max_precond_dim: int = ...,
        momentum_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class HeavySOLP(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        shampoo_beta: float = ...,
        preconditioner_update_probability: float = ...,
        max_precond_dim: int = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class HyperBallAdamW(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        caution: float = ...,
        cautious_weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class KLSOAP(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        shampoo_beta: float = ...,
        preconditioner_update_probability: float = ...,
        max_precond_dim: int = ...,
        init_factor: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class KLShampoo(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        preconditioner_update_probability: float = ...,
        max_precond_dim: int = ...,
        init_factor: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class LATHER(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        preconditioner_update_probability: float = ...,
        precond_lr: float = ...,
        lower_bound_beta: float = ...,
        dampening: float = ...,
        max_size_triangular: int = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class LaProp(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class LaPropOrtho(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class Lion(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class MARSAdamW(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        mars_gamma: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class MSAM(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        sam_step_size: float = ...,
        caution: float = ...,
        cautious_weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class Muon(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class MuonLaProp(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class NAdam(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        momentum_decay: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class NorMuon(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class Oblique(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class OrthoGradAdamW(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class OrthoLaProp(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class PSGD(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        preconditioner_update_probability: float = ...,
        precond_lr: float = ...,
        lower_bound_beta: float = ...,
        dampening: float = ...,
        max_size_triangular: int = ...,
        weight_decay: float = ...,
        rank: int = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class PSGDKron(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        preconditioner_update_probability: float = ...,
        precond_lr: float = ...,
        lower_bound_beta: float = ...,
        dampening: float = ...,
        max_size_triangular: int = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class PSGDLRA(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        preconditioner_update_probability: float = ...,
        precond_lr: float = ...,
        dampening: float = ...,
        rank: int = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class PSGDNfactor(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        preconditioner_update_probability: float = ...,
        precond_lr: float = ...,
        lower_bound_beta: float = ...,
        dampening: float = ...,
        max_size_triangular: int = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class PSGDPro(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        preconditioner_update_probability: float = ...,
        precond_lr: float = ...,
        lower_bound_beta: float = ...,
        dampening: float = ...,
        max_size_triangular: int = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class PolarGrad(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class QSGD(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        preconditioner_update_probability: float = ...,
        precond_lr: float = ...,
        lower_bound_beta: float = ...,
        dampening: float = ...,
        max_size_triangular: int = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class RMSprop(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class SFAdamW(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        weight_lr_power: float = ...,
        r: float = ...,
        caution: float = ...,
        cautious_weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class SGD(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class SOAP(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        shampoo_beta: float = ...,
        preconditioner_update_probability: float = ...,
        max_precond_dim: int = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class SOAPAdEMAMix(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        shampoo_beta: float = ...,
        preconditioner_update_probability: float = ...,
        max_precond_dim: int = ...,
        beta3: float = ...,
        alpha: float = ...,
        beta3_warmup: float = ...,
        alpha_warmup: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class SOAPNAdam(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        shampoo_beta: float = ...,
        preconditioner_update_probability: float = ...,
        max_precond_dim: int = ...,
        momentum_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class SOLP(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        shampoo_beta: float = ...,
        preconditioner_update_probability: float = ...,
        max_precond_dim: int = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class SpEL(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class SUDSAdamW(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        precond_lr: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class ScheduleFree(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        weight_lr_power: float = ...,
        r: float = ...,
        caution: float = ...,
        cautious_weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class Scion(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        eps: float = ...,
        scale: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class Shampoo(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        preconditioner_update_probability: float = ...,
        max_precond_dim: int = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class SignLaProp(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class SignSGD(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class TrueGradAdam(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class TrueGradLaProp(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class TrueGradNAdam(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        momentum_decay: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class TrueGradRMSprop(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class UnscaledAdamW(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class WhitenAdamW(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        preconditioner_update_probability: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class Whitening(HeavyBallOptimizer):
    def __init__(
        self,
        params: Iterable[Tensor] | Iterable[Mapping[str, object]],
        *,
        lr: float = ...,
        beta1: float = ...,
        beta2: float = ...,
        eps: float = ...,
        weight_decay: float = ...,
        preconditioner_update_probability: float = ...,
        storage_dtype: torch.dtype | str | None = ...,
        ecc: int | str | None = ...,
        clip_global_norm: float | None = ...,
        param_keys: Sequence[str] | None = ...,
    ) -> None: ...


class SplitOpt(Optimizer):
    def __init__(self, specs: Sequence[dict[str, object]]) -> None: ...


__all__ = [
    "ADOPT",
    "AdEMAMix",
    "AdaMuon",
    "AdamC",
    "AdamW",
    "Aurora",
    "CautiousAdamW",
    "HeavyBallOptimizer",
    "HeavyKLSOAP",
    "HeavyKLShampoo",
    "HeavySOAP",
    "HeavySOAPAdEMAMix",
    "HeavySOAPNAdam",
    "HeavySOLP",
    "HyperBallAdamW",
    "KLSOAP",
    "KLShampoo",
    "LATHER",
    "LaProp",
    "LaPropOrtho",
    "Lion",
    "MARSAdamW",
    "MSAM",
    "Muon",
    "MuonLaProp",
    "NAdam",
    "NorMuon",
    "Oblique",
    "OrthoGradAdamW",
    "OrthoLaProp",
    "PSGD",
    "PSGDKron",
    "PSGDLRA",
    "PSGDNfactor",
    "PSGDPro",
    "PolarGrad",
    "QSGD",
    "RMSprop",
    "SFAdamW",
    "SGD",
    "SOAP",
    "SOAPAdEMAMix",
    "SOAPNAdam",
    "SOLP",
    "SpEL",
    "SUDSAdamW",
    "ScheduleFree",
    "Scion",
    "Shampoo",
    "SignLaProp",
    "SignSGD",
    "SplitOpt",
    "TrueGradAdam",
    "TrueGradLaProp",
    "TrueGradNAdam",
    "TrueGradRMSprop",
    "UnscaledAdamW",
    "WhitenAdamW",
    "Whitening",
]
